# Generated by Django 3.2.7 on 2021-12-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Repos', '0002_auto_20211225_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_branch', models.CharField(max_length=120)),
                ('feature_branch', models.CharField(max_length=120)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_author', to=settings.AUTH_USER_MODEL)),
                ('base_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_repo', to='Repos.repo')),
                ('feature_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_repo', to='Repos.repo')),
            ],
        ),
    ]
