# Generated by Django 3.2.8 on 2021-10-15 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Repos', '0002_alter_repo_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
