# Generated by Django 3.2.8 on 2021-10-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repos', '0003_alter_repo_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='name',
            field=models.CharField(default='s', max_length=30),
            preserve_default=False,
        ),
    ]
