# Generated by Django 3.2.8 on 2021-10-15 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Repos', '0004_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Repos.repo'),
        ),
        migrations.AddField(
            model_name='repo',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='star', to=settings.AUTH_USER_MODEL),
        ),
    ]
