# Generated by Django 3.2.8 on 2021-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repos', '0006_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
