# Generated by Django 3.2.8 on 2021-12-12 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Repos', '0007_repo_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.SmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('thatGuy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thatGuy', to=settings.AUTH_USER_MODEL)),
                ('thatRepo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Repos.repo')),
                ('thisGuy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisGuy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
