# Generated by Django 3.2.8 on 2021-12-15 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repos', '0008_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
