# Generated by Django 4.0 on 2021-12-27 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 13, 44, 11, 666125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='expiration_seconds',
            field=models.BigIntegerField(default=300),
        ),
    ]
